apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
spec:
  type: LoadBalancer
  ports:
    - port:  5432
      targetPort:  5432
      protocol: TCP
      name: postgresql
  selector:
    app: postgres
