apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  patroni.yaml: |
    bootstrap:
      dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
          use_pg_rewind: true
          parameters:
            archive_mode: "on"
            archive_command: "cd ."
            max_wal_senders: 10
            max_connections: 100
            wal_level: hot_standby
            max_wal_size: 10GB
            min_wal_size: 1GB
            checkpoint_timeout: 30s
            checkpoint_completion_target: 0.9
            archive_timeout: 60
    scope: patroni
    restapi:
      listen: 0.0.0.0:8008
      connect_address: '{{ POD_IP }}:8008'
    postgresql:
      listen: 0.0.0.0:5432
      connect_address: '{{ POD_IP }}:5432'
      data_dir: /var/lib/postgresql/data
